version: "~> 1.0"
os: windows
language: python
python:
- '3.6'
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: s66MWlPsJVN0XGc+/ls/KdXah0tvdd8Z8ukqnUTrcTOkPSYS4OR8MNaSUxmxSaADNNxZwstVXN4yz5g+RdUWGBASz0RH9083Z3wNjHWM1s6J2f1fia3Kr4G8u+dRcNpNQoUqk1ti9u54/iZFMQBDjCcRgR28guQ6UruoG4FWrZXQ+zV/qrteWf/AVBPkO6wpyZWEY21KsysA81ktR2NxTMmxpA+JO7OS3afP2Kec1T6usa8mpYj7Wgn/NJyeKnAfEA2Cj/R7t3VmcXHgLNXQkxQedixOIKrOjoYKSbIUxB5CUsozWUxqKYruZ934tCPdSTvjqOynojdTkaRClPvreLv0JtaPwcoU7AqEqjgjM85m530barM37zV1Vj9Vgx5ppMRTWZqCnugL8PL0VtTsJQB0TYPuJkZRu1NLu3257tT8Bunj3ywfrX+udOf3t542jjwrf2BmXdx+y6D/rawvtlUiKsEJi7V53upybMV9CyU6fxyyG2mk7AbUniTX3OSWV0wC6Cv0g8wLO+7G2tpvXPCaFiOt5fMpWKPf8kFqp0u8nxbPTXrIJjcNgMeuPjAHLKBA4fBdxDPBNQBgD5RSuVWRCE8s7tEH3ynUsj7v/vETuqM/napG0j56K/w09a7ic+3xtNuCdWncidh20BnQn4HmMlDocyU4oLdf/P8lksI=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
install:
- pip install -r requirements.txt
- ansible-galaxy install -r requirements.yml
- curl -sSLo merge.sh https://raw.githubusercontent.com/ckaserer/git-merge-script/master/merge.sh
- chmod a+x merge.sh
env:
  jobs:
  - SCENARIO=default
  global:
    secure: jmca6Bz6Ug20yldPHs6H7L9IKt1uHnK5mJnhwhTN3n1WIexb9f9lOmWTMN5OjyffdHUcNq4Oozq+LTXj4KV6nHCfyH19zfMZDFbw4L6Wx0BaR4DFuu8SnAyhSIPBbKi09nPCmB9gPWyOzr8bCx8oWDO7Kv+99On7manOqDMbnSBa7LL7/lB638ZqaS/6BsSLlRkKAW4Sg8JmreH/PC3d97RramBAdnf4TCnfs1LGrJ+Ez92zFHOMlTWe4AIObMo+JcFT0LhdFIuCgFcrbDgaIWH6O4Cu8ddy2QHI6RYZSdgY5mlKpsYKXjomphtaGRzeYgCkAZnCnlrajDJPREuoXk1BgboQK7/LexLlubfnDOTmO6EN7qNA2iTEQn9r336zNAGhG0iYnnkje/w9pVtvhStBZQ/7mrpP7J40rfgNcvl2Z6PbMqstGH6Jc3DbBJGwqyMLUEXXWpgN18XrKj6Dymgi4CSRmMTShGMfOyc19C+HmvyTQm+rP8/sokr9EA/IIlU/Z3gaGwpGIvvamP8yK1+4QcoUXpheh+Q61zsszgI77XczpDSbVDdQ6dF2/8Nqi3H5l9JrFj02Y7O42+OBdfYiEEiMrYclLl7JGhUgqpladvMtXorWL9jdKTibphYZZ61N/sNbc0z5sJWD01YXc/2YcS+D2t1eAdeTWQS7aoM=
script:
- molecule test --scenario-name ${SCENARIO}
after_success:
- BRANCHES_TO_MERGE_REGEX='^develop' BRANCH_TO_MERGE_INTO=master ./merge.sh